a=3
b=5
print(2*a*b*3)
("------x------")
salario=1500
aumento=80000
print(salario+(salario*aumento/100))
print("------x-----")
S = "miguel"
print(S[0])
print(S[2:3])
("-----x-----")
s="miguel jose gomes da silva freitas"
print(s.startswith("miguel"))
print(s.endswith("jose"))
print("another".find("other"))
print("cheat".replace("mi", "ss"))
s="miguel\njose\ngomes\nda\nsilva\nfreitas"